//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class laboratorioEntities : DbContext
    {
        public laboratorioEntities()
            : base("name=laboratorioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrera> carreras { get; set; }
        public virtual DbSet<estadoReservacion> estadoReservacions { get; set; }
        public virtual DbSet<estudiante> estudiantes { get; set; }
        public virtual DbSet<facultad> facultads { get; set; }
        public virtual DbSet<genero> generoes { get; set; }
        public virtual DbSet<horario> horarios { get; set; }
        public virtual DbSet<laboratorio> laboratorios { get; set; }
        public virtual DbSet<opcion> opcions { get; set; }
        public virtual DbSet<reservacion> reservacions { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<rolOpcion> rolOpcions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tipoReservacion> tipoReservacions { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<usuarioRol> usuarioRols { get; set; }
    }
}
