//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservacion
    {
        public int idReservacion { get; set; }
        public string observacion { get; set; }
        public int idLaboratorio { get; set; }
        public int idUsuario { get; set; }
        public int idEstudiante { get; set; }
        public System.TimeSpan horaEntrada { get; set; }
        public System.TimeSpan horaSalida { get; set; }
        public int idTipoReservacion { get; set; }
        public int idEstadoReservacion { get; set; }
        public int idHorario { get; set; }
        public System.DateTime fechaReservacion { get; set; }
    
        public virtual estadoReservacion estadoReservacion { get; set; }
        public virtual estudiante estudiante { get; set; }
        public virtual horario horario { get; set; }
        public virtual laboratorio laboratorio { get; set; }
        public virtual tipoReservacion tipoReservacion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
