//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolOpcion
    {
        public int idRolOpcion { get; set; }
        public int idOpcion { get; set; }
        public int idRol { get; set; }
    
        public virtual opcion opcion { get; set; }
        public virtual rol rol { get; set; }
    }
}
